### ISSUE TITLE
In .Net Core Gauge project, step implementation is not recognized when in it is in the referenced project

### ISSUE THREAD

**Issue by jenniferz79** [getgauge/gauge-dotnet#51] opened 2019-12-14 04:32 UTC
Steps to Reproduce
-----------------------
* Create a Gauge Test Project: project1
* Add another Gauge Test Project: project2 in the same solution.
* In project2, create spec file.
* In project1, create steps implementation.
* In project2 add reference to project1.
* Use command to 'gauge run specs'

Actual Behavior
---------------------
Exceptions thrown, showing step implementation not found.

Expected Behaviour
----------------------
Step should be recognized, and goto-defn should work.

Tried the same way on gauge-csharp, it works fine. This problem only happens on gauge-dotnet.

**Comment by shubhamsc** [comment] 2019-12-16 06:36
@jenniferz79  Thanks for reporting this problem.
I can replicate the same with gauge-dotnet. Gauge team will look into it soon.

**Comment by jenniferz79** [comment] 2020-01-15 03:45
Hi, is there any update for this issue? Thanks~

**Comment by sriv** [comment] 2020-01-16 04:48
hi - we are working on changing the underlying mechanism used for gauge and it's plugins (the newer versions will be using gRPC) - this is in the backlog and will get picked up post that.

**Comment by jenniferz79** [comment] 2020-02-12 04:25
Hi there,
Just want to ask, when this issue will be planned to be picked? Sorry for keeping asking, as my team is trying to make decision on whether choose gauge as our automation test framework, and this issue is very crucial (a big blocking issue) for our decision making. Thanks~

**Comment by sriv** [comment] 2020-02-12 04:37
hi @jenniferz79 - appreciate your patience. We made a release for gauge `1.0.7` just yesterday and the plugins should follow. You should be able to see the dotnet plugin `1.0.3` released soon and this should address your case.

Thanks for trying Gauge.

**Comment by sriv** [comment] 2020-02-12 07:47
I replied in haste, apologies. This is yet to be fixed. I spent some time to analyze the cause, findings below.

### Dev Notes
When Static Parsing was introduced, it assumed that the implementations will be in `GAUGE_PROJECT_ROOT` or it's subfolders. This is not the case in a referenced project.

Note that the referenced project is built when `gauge run` is invoed, the assembly is copied over to `gauge_bin`. Furthermore, gauge-dotnet loads, scans and adds these implemented methods to the `StepRegistry`.

This is not done at the time of Validation, and hence it is skipped for execution. This should be fixed starting at [`StaticLoader.LoadImplementations`](https://github.com/getgauge/gauge-dotnet/blob/master/src/StaticLoader.cs#L78)

**Comment by jenniferz79** [comment] 2020-02-13 01:58
@sriv , thanks for the quick response, and analyze, which is very helpful.
I tried to tweak the implementation in StaticLoader.LoadImplementations a bit, and it does fix the issue.
So we decide to start using gauge-dotnet plugin with my local modification temporarily, it is kind of workaround.
Please let me know when you release fix for it officially, hope it will be soon.
Thanks again for your help, as it does help us move on.

**Comment by sriv** [comment] 2020-02-13 02:03
@jenniferz79 - great news! Would you be interested in submitting a PR?

**Comment by jenniferz79** [comment] 2020-02-13 20:26
@sriv , my local modification is just a temporary workaround for now. To use it would need to export new environment variable. I don't think this solution is good enough to put into main repo. That's why I am still hoping we can get this issue solved officially.
I plan to spend more time to see if I can get better solution for it. If I find one, I will let you know.
Please also let me know if you solve it officially. Thanks~

**Closed** 2020-03-19 09:50 UTC

**Comment by jenniferz79** [comment] 2020-03-25 00:56
@sriv I checked out your latest fix for dotnet. It seems work, I can run the case with reference project as below. 
```
# Specification Heading
  ## Vowel counts in single word
Reference project path: c:\Users\jennifer.z\source\repos\GaugeCore\GaugeCore_Framework
  ## Vowel counts in multiple word
```
But, when I am trying to use vscode IDE, to click the step in specs, it still can not find step implementation in referenced project. Gauge vscode plugin showing error as below:
```
request #10: textDocument/definition: implementation source not found: Step implementation referred from an external project or library
[Error - 1:50:26 pm] Request textDocument/definition failed.
  Message: implementation source not found: Step implementation referred from an external project or library
  Code: 0 
```
Does it mean the vscode plugin also needs some update for this referenced project steps working?
Thanks~

**Comment by sriv** [comment] 2020-03-25 10:26
@jenniferz79 
>   Message: implementation source not found: Step implementation referred from an external project or library

this is by design, because there isn't an obvious way to show definitions from a project that may not be loaded. If you have any suggestions, we are all ears!

That said, you should still be able to execute the project.

**Comment by jenniferz79** [comment] 2020-03-25 20:36
@sriv thanks for the reply.
One more question, while we are referencing steps implemented in the other project, and that project is being loaded and opened, in the same solution, in vscode IDE, can we go to the steps implementation by ctrl-click the steps in spec?
In visual studio IDE, .net framework gauge, it support to find the steps implementation in the same solution but different project.
I really hope vscode IDE gauge plugin would support the same, else it is impossible to make spec files while the steps are not in the same project, and can't be found.
Execute project is fine, but before execute project, we first have to have tests in project. How to put those tests in project while we have no insight of the steps implementation?

**Comment by jenniferz79** [comment] 2020-03-30 04:39
@sriv , how are you doing? 
Our company is in the decision making on whether to use Gauge or not? If possible, could you help give us some info on future Gauge development?
- I found in the Gauge homepage, now only vscode IDE is supported. Does it mean Gauge decided to shrink only support vscode in the long run?
- How Gauge is planning to support multiple projects, e.g. steps and specs in different projects? As our company is planning to use gauge in 5 different teams' automation, we need share steps in different projects. So this is very important for us.
- How will gauge support one solution with multiple projects in vscode plugin? As I said before, currently if I open a solution with multiple projects, I can not see the definitions across the projects. Will this be solved in the future?

Thanks for your help all the time~

**Comment by zabil** [comment] 2020-03-30 08:42
> Our company is in the decision making on whether to use Gauge or not? If possible, could you help give us some info on future Gauge development?

Sure

>  found in the Gauge homepage, now only vscode IDE is supported. Does it mean Gauge decided to shrink only support vscode in the long run?

Yes

> How Gauge is planning to support multiple projects, e.g. steps and specs in different projects? As our company is planning to use gauge in 5 different teams' automation, we need share steps in different projects. So this is very important for us.

Right now you can share steps across projects and the tests will run fine. It's only the IDE part of jumping across defnitions in other projects that do not work. Unfortunately, it's difficult implement these IDE features and not being worked upon any time soon as there are other issues with higher priority. Any help is appreciated.

> Will this be solved in the future?

At this point, no.

**Comment by jenniferz79** [comment] 2020-03-31 20:08
@zabil , thank you for your reply.
