### ISSUE TITLE
gauge-dotnet using different thread id in one run, which causes problem if using webdriver ThreadLocal

### ISSUE THREAD

**Issue by jenniferz79** [getgauge/gauge-dotnet#68] opened 2020-04-06 22:33 UTC
Steps to Reproduce
-----------------------
* Create a gauge dotnet project, netstandard 2.0
* In the every example steps implementation, add print to print thread id as below:
```
Console.WriteLine("thread: " + Thread.CurrentThread.ManagedThreadId);
```
* Then run the spec
```
Gauge version: 1.0.8
Commit Hash: 28617ea

Plugins
-------
csharp (0.10.6)
dotnet (0.1.3)
html-report (4.0.10)
java (0.7.4)
js (2.3.8)
reportportal (1.1.0)
screenshot (0.0.1)
xml-report (0.2.3)
```
Actual Behavior
---------------------
It turned out the thread id is changing in the same run, which is quite wired. Is it as designed?
```
# Specification Heading
  ## Vowel counts in single word        thread: 14
 Pthread: 13
thread: 13
 P
  ## Vowel counts in multiple word      thread: 15
 Pthread: 15
thread: 15
thread: 15
thread: 15
thread: 15
thread: 15
```

Expected Behaviour
----------------------
Thread ID should be the same if not enable multi-threading. In gauge csharp, it works fine, but in gauge dotnet, the thread id strangely changes all the time. I found this problem, when we are moving from csharp to dotnet, as gauge deprecated csharp recently.
In our Selenium Web Ui implementation, we use ThreadLocal to store webdriver per thread. It will try to get webdriver in ThreadLocal, if null, it will create webdriver, else will use the existed one. As thread id is changing, so every time it creates a new webdriver, open a new browser window, which is very strange.
I know currently gauge dotnet/csharp only support multi-process, not multi-threading, but such 'unexpected multi-threading' is definitely potential problem, unless we have a good reason for it?

**Comment by sriv** [comment] 2020-04-07 11:09
gauge-dotnet (and gauge) now use gRPC to communicate, which by design uses threads to process the requests. gauge-dotnet does not intentionally do this.

I think I understand your use case, I am trying to think of a clean way to achieve this. Would you have a sample project where I can see webdriver being used as ThreadLocal?

**Comment by sriv** [comment] 2020-04-07 12:40
Note that you can use `Datastores` to persist objects. You can choose a datastore depending on how long you'd like the object to live. Does this help?

**Comment by jenniferz79** [comment] 2020-04-07 20:43
@sriv , thanks for the reply.

* Why gauge csharp does not have this problem? Only dotnet is having this unexpected multi-threading. 

* The whole implementation of webdriver includes many classes, and it is not convenient to share the whole repo. But the idea is similar to this: https://consolidatedchaos.com/2018/11/07/design-selenium-framework-with-c-part-3/

* Actually, I have changed the webdriver implementation to be Singleton, as we know Gauge dotnet does not support multithreading, so another workaround for gauge again.

* I would prefer not to use 'Datastores' to save webdriver, as the webdriver is neither related with scenario/steps/suit, that's another concept.

**Comment by zabil** [comment] 2020-04-08 08:19
> Why gauge csharp does not have this problem? Only dotnet is having this unexpected multi-threading.

Unlike the csharp plugin the dotnet plugin uses a completely different technology (grpc) this relies on a different threading mechanism. That way the dotnet plugin is very different, for the better.

> Actually, I have changed the webdriver implementation to be Singleton, as we know Gauge dotnet does not support multithreading, so another workaround for gauge again.

This is the right way of doing it. Even in the samples of Gauge, the webdriver instance is passed around as a singleton.

Thanks for pointing this out. The recommended way of passing webdriver is using singletons. Closing this issue for now as the dotnet threading mechanism will not be changed.

**Closed by zabil** 2020-04-08 08:19 UTC
